export interface SelectOption {
  value: string
  label: string
  group: string
  meta?: string
}

export const COUNTRIES: SelectOption[] = [
  // Africa
  { value: "dz", label: "Algeria", group: "Africa", meta: "Arabic" },
  { value: "ao", label: "Angola", group: "Africa", meta: "Portuguese" },
  { value: "bj", label: "Benin", group: "Africa", meta: "French" },
  { value: "bw", label: "Botswana", group: "Africa", meta: "English" },
  { value: "bf", label: "Burkina Faso", group: "Africa", meta: "French" },
  { value: "bi", label: "Burundi", group: "Africa", meta: "French" },
  { value: "cv", label: "Cape Verde", group: "Africa", meta: "Portuguese" },
  { value: "cm", label: "Cameroon", group: "Africa", meta: "French" },
  { value: "cf", label: "Central African Republic", group: "Africa", meta: "French" },
  { value: "td", label: "Chad", group: "Africa", meta: "French" },
  { value: "km", label: "Comoros", group: "Africa", meta: "Arabic" },
  { value: "cd", label: "Congo (DRC)", group: "Africa", meta: "French" },
  { value: "cg", label: "Congo (Republic)", group: "Africa", meta: "French" },
  { value: "ci", label: "Côte d'Ivoire", group: "Africa", meta: "French" },
  { value: "dj", label: "Djibouti", group: "Africa", meta: "French" },
  { value: "eg", label: "Egypt", group: "Africa", meta: "Arabic" },
  { value: "gq", label: "Equatorial Guinea", group: "Africa", meta: "Spanish" },
  { value: "er", label: "Eritrea", group: "Africa", meta: "Tigrinya" },
  { value: "sz", label: "Eswatini", group: "Africa", meta: "Swati" },
  { value: "et", label: "Ethiopia", group: "Africa", meta: "Amharic" },
  { value: "ga", label: "Gabon", group: "Africa", meta: "French" },
  { value: "gm", label: "Gambia", group: "Africa", meta: "English" },
  { value: "gh", label: "Ghana", group: "Africa", meta: "English" },
  { value: "gn", label: "Guinea", group: "Africa", meta: "French" },
  { value: "gw", label: "Guinea-Bissau", group: "Africa", meta: "Portuguese" },
  { value: "ke", label: "Kenya", group: "Africa", meta: "Swahili" },
  { value: "ls", label: "Lesotho", group: "Africa", meta: "Sesotho" },
  { value: "lr", label: "Liberia", group: "Africa", meta: "English" },
  { value: "ly", label: "Libya", group: "Africa", meta: "Arabic" },
  { value: "mg", label: "Madagascar", group: "Africa", meta: "Malagasy" },
  { value: "mw", label: "Malawi", group: "Africa", meta: "Chichewa" },
  { value: "ml", label: "Mali", group: "Africa", meta: "French" },
  { value: "mr", label: "Mauritania", group: "Africa", meta: "Arabic" },
  { value: "mu", label: "Mauritius", group: "Africa", meta: "English" },
  { value: "ma", label: "Morocco", group: "Africa", meta: "Arabic" },
  { value: "mz", label: "Mozambique", group: "Africa", meta: "Portuguese" },
  { value: "na", label: "Namibia", group: "Africa", meta: "English" },
  { value: "ne", label: "Niger", group: "Africa", meta: "French" },
  { value: "ng", label: "Nigeria", group: "Africa", meta: "English" },
  { value: "rw", label: "Rwanda", group: "Africa", meta: "Kinyarwanda" },
  { value: "st", label: "São Tomé and Príncipe", group: "Africa", meta: "Portuguese" },
  { value: "sn", label: "Senegal", group: "Africa", meta: "French" },
  { value: "sc", label: "Seychelles", group: "Africa", meta: "French" },
  { value: "sl", label: "Sierra Leone", group: "Africa", meta: "English" },
  { value: "so", label: "Somalia", group: "Africa", meta: "Somali" },
  { value: "za", label: "South Africa", group: "Africa", meta: "Zulu" },
  { value: "ss", label: "South Sudan", group: "Africa", meta: "English" },
  { value: "sd", label: "Sudan", group: "Africa", meta: "Arabic" },
  { value: "tz", label: "Tanzania", group: "Africa", meta: "Swahili" },
  { value: "tg", label: "Togo", group: "Africa", meta: "French" },
  { value: "tn", label: "Tunisia", group: "Africa", meta: "Arabic" },
  { value: "ug", label: "Uganda", group: "Africa", meta: "English" },
  { value: "zm", label: "Zambia", group: "Africa", meta: "English" },
  { value: "zw", label: "Zimbabwe", group: "Africa", meta: "English" },

  // Americas
  { value: "ag", label: "Antigua and Barbuda", group: "Americas", meta: "English" },
  { value: "ar", label: "Argentina", group: "Americas", meta: "Spanish" },
  { value: "bs", label: "Bahamas", group: "Americas", meta: "English" },
  { value: "bb", label: "Barbados", group: "Americas", meta: "English" },
  { value: "bz", label: "Belize", group: "Americas", meta: "English" },
  { value: "bo", label: "Bolivia", group: "Americas", meta: "Spanish" },
  { value: "br", label: "Brazil", group: "Americas", meta: "Portuguese" },
  { value: "ca", label: "Canada", group: "Americas", meta: "English" },
  { value: "cl", label: "Chile", group: "Americas", meta: "Spanish" },
  { value: "co", label: "Colombia", group: "Americas", meta: "Spanish" },
  { value: "cr", label: "Costa Rica", group: "Americas", meta: "Spanish" },
  { value: "cu", label: "Cuba", group: "Americas", meta: "Spanish" },
  { value: "dm", label: "Dominica", group: "Americas", meta: "English" },
  { value: "do", label: "Dominican Republic", group: "Americas", meta: "Spanish" },
  { value: "ec", label: "Ecuador", group: "Americas", meta: "Spanish" },
  { value: "sv", label: "El Salvador", group: "Americas", meta: "Spanish" },
  { value: "gd", label: "Grenada", group: "Americas", meta: "English" },
  { value: "gt", label: "Guatemala", group: "Americas", meta: "Spanish" },
  { value: "gy", label: "Guyana", group: "Americas", meta: "English" },
  { value: "ht", label: "Haiti", group: "Americas", meta: "French" },
  { value: "hn", label: "Honduras", group: "Americas", meta: "Spanish" },
  { value: "jm", label: "Jamaica", group: "Americas", meta: "English" },
  { value: "mx", label: "Mexico", group: "Americas", meta: "Spanish" },
  { value: "ni", label: "Nicaragua", group: "Americas", meta: "Spanish" },
  { value: "pa", label: "Panama", group: "Americas", meta: "Spanish" },
  { value: "py", label: "Paraguay", group: "Americas", meta: "Spanish" },
  { value: "pe", label: "Peru", group: "Americas", meta: "Spanish" },
  { value: "kn", label: "Saint Kitts and Nevis", group: "Americas", meta: "English" },
  { value: "lc", label: "Saint Lucia", group: "Americas", meta: "English" },
  { value: "vc", label: "Saint Vincent and the Grenadines", group: "Americas", meta: "English" },
  { value: "sr", label: "Suriname", group: "Americas", meta: "Dutch" },
  { value: "tt", label: "Trinidad and Tobago", group: "Americas", meta: "English" },
  { value: "us", label: "United States", group: "Americas", meta: "English" },
  { value: "uy", label: "Uruguay", group: "Americas", meta: "Spanish" },
  { value: "ve", label: "Venezuela", group: "Americas", meta: "Spanish" },

  // Asia
  { value: "af", label: "Afghanistan", group: "Asia", meta: "Pashto" },
  { value: "am", label: "Armenia", group: "Asia", meta: "Armenian" },
  { value: "az", label: "Azerbaijan", group: "Asia", meta: "Azerbaijani" },
  { value: "bh", label: "Bahrain", group: "Asia", meta: "Arabic" },
  { value: "bd", label: "Bangladesh", group: "Asia", meta: "Bengali" },
  { value: "bt", label: "Bhutan", group: "Asia", meta: "Dzongkha" },
  { value: "bn", label: "Brunei", group: "Asia", meta: "Malay" },
  { value: "kh", label: "Cambodia", group: "Asia", meta: "Khmer" },
  { value: "cn", label: "China", group: "Asia", meta: "Mandarin" },
  { value: "cy", label: "Cyprus", group: "Asia", meta: "Greek" },
  { value: "ge", label: "Georgia", group: "Asia", meta: "Georgian" },
  { value: "in", label: "India", group: "Asia", meta: "Hindi" },
  { value: "id", label: "Indonesia", group: "Asia", meta: "Indonesian" },
  { value: "ir", label: "Iran", group: "Asia", meta: "Persian" },
  { value: "iq", label: "Iraq", group: "Asia", meta: "Arabic" },
  { value: "il", label: "Israel", group: "Asia", meta: "Hebrew" },
  { value: "jp", label: "Japan", group: "Asia", meta: "Japanese" },
  { value: "jo", label: "Jordan", group: "Asia", meta: "Arabic" },
  { value: "kz", label: "Kazakhstan", group: "Asia", meta: "Kazakh" },
  { value: "kw", label: "Kuwait", group: "Asia", meta: "Arabic" },
  { value: "kg", label: "Kyrgyzstan", group: "Asia", meta: "Kyrgyz" },
  { value: "la", label: "Laos", group: "Asia", meta: "Lao" },
  { value: "lb", label: "Lebanon", group: "Asia", meta: "Arabic" },
  { value: "my", label: "Malaysia", group: "Asia", meta: "Malay" },
  { value: "mv", label: "Maldives", group: "Asia", meta: "Dhivehi" },
  { value: "mn", label: "Mongolia", group: "Asia", meta: "Mongolian" },
  { value: "mm", label: "Myanmar", group: "Asia", meta: "Burmese" },
  { value: "np", label: "Nepal", group: "Asia", meta: "Nepali" },
  { value: "kp", label: "North Korea", group: "Asia", meta: "Korean" },
  { value: "om", label: "Oman", group: "Asia", meta: "Arabic" },
  { value: "pk", label: "Pakistan", group: "Asia", meta: "Urdu" },
  { value: "ps", label: "Palestine", group: "Asia", meta: "Arabic" },
  { value: "ph", label: "Philippines", group: "Asia", meta: "Filipino" },
  { value: "qa", label: "Qatar", group: "Asia", meta: "Arabic" },
  { value: "sa", label: "Saudi Arabia", group: "Asia", meta: "Arabic" },
  { value: "sg", label: "Singapore", group: "Asia", meta: "English" },
  { value: "kr", label: "South Korea", group: "Asia", meta: "Korean" },
  { value: "lk", label: "Sri Lanka", group: "Asia", meta: "Sinhala" },
  { value: "sy", label: "Syria", group: "Asia", meta: "Arabic" },
  { value: "tw", label: "Taiwan", group: "Asia", meta: "Mandarin" },
  { value: "tj", label: "Tajikistan", group: "Asia", meta: "Tajik" },
  { value: "th", label: "Thailand", group: "Asia", meta: "Thai" },
  { value: "tl", label: "Timor-Leste", group: "Asia", meta: "Portuguese" },
  { value: "tm", label: "Turkmenistan", group: "Asia", meta: "Turkmen" },
  { value: "ae", label: "United Arab Emirates", group: "Asia", meta: "Arabic" },
  { value: "uz", label: "Uzbekistan", group: "Asia", meta: "Uzbek" },
  { value: "vn", label: "Vietnam", group: "Asia", meta: "Vietnamese" },
  { value: "ye", label: "Yemen", group: "Asia", meta: "Arabic" },

  // Europe
  { value: "al", label: "Albania", group: "Europe", meta: "Albanian" },
  { value: "ad", label: "Andorra", group: "Europe", meta: "Catalan" },
  { value: "at", label: "Austria", group: "Europe", meta: "German" },
  { value: "by", label: "Belarus", group: "Europe", meta: "Belarusian" },
  { value: "be", label: "Belgium", group: "Europe", meta: "Dutch" },
  { value: "ba", label: "Bosnia and Herzegovina", group: "Europe", meta: "Bosnian" },
  { value: "bg", label: "Bulgaria", group: "Europe", meta: "Bulgarian" },
  { value: "hr", label: "Croatia", group: "Europe", meta: "Croatian" },
  { value: "cz", label: "Czech Republic", group: "Europe", meta: "Czech" },
  { value: "dk", label: "Denmark", group: "Europe", meta: "Danish" },
  { value: "ee", label: "Estonia", group: "Europe", meta: "Estonian" },
  { value: "fi", label: "Finland", group: "Europe", meta: "Finnish" },
  { value: "fr", label: "France", group: "Europe", meta: "French" },
  { value: "de", label: "Germany", group: "Europe", meta: "German" },
  { value: "gr", label: "Greece", group: "Europe", meta: "Greek" },
  { value: "hu", label: "Hungary", group: "Europe", meta: "Hungarian" },
  { value: "is", label: "Iceland", group: "Europe", meta: "Icelandic" },
  { value: "ie", label: "Ireland", group: "Europe", meta: "English" },
  { value: "it", label: "Italy", group: "Europe", meta: "Italian" },
  { value: "xk", label: "Kosovo", group: "Europe", meta: "Albanian" },
  { value: "lv", label: "Latvia", group: "Europe", meta: "Latvian" },
  { value: "li", label: "Liechtenstein", group: "Europe", meta: "German" },
  { value: "lt", label: "Lithuania", group: "Europe", meta: "Lithuanian" },
  { value: "lu", label: "Luxembourg", group: "Europe", meta: "Luxembourgish" },
  { value: "mt", label: "Malta", group: "Europe", meta: "Maltese" },
  { value: "md", label: "Moldova", group: "Europe", meta: "Romanian" },
  { value: "mc", label: "Monaco", group: "Europe", meta: "French" },
  { value: "me", label: "Montenegro", group: "Europe", meta: "Montenegrin" },
  { value: "nl", label: "Netherlands", group: "Europe", meta: "Dutch" },
  { value: "mk", label: "North Macedonia", group: "Europe", meta: "Macedonian" },
  { value: "no", label: "Norway", group: "Europe", meta: "Norwegian" },
  { value: "pl", label: "Poland", group: "Europe", meta: "Polish" },
  { value: "pt", label: "Portugal", group: "Europe", meta: "Portuguese" },
  { value: "ro", label: "Romania", group: "Europe", meta: "Romanian" },
  { value: "ru", label: "Russia", group: "Europe", meta: "Russian" },
  { value: "sm", label: "San Marino", group: "Europe", meta: "Italian" },
  { value: "rs", label: "Serbia", group: "Europe", meta: "Serbian" },
  { value: "sk", label: "Slovakia", group: "Europe", meta: "Slovak" },
  { value: "si", label: "Slovenia", group: "Europe", meta: "Slovenian" },
  { value: "es", label: "Spain", group: "Europe", meta: "Spanish" },
  { value: "se", label: "Sweden", group: "Europe", meta: "Swedish" },
  { value: "ch", label: "Switzerland", group: "Europe", meta: "German" },
  { value: "tr", label: "Turkey", group: "Europe", meta: "Turkish" },
  { value: "ua", label: "Ukraine", group: "Europe", meta: "Ukrainian" },
  { value: "gb", label: "United Kingdom", group: "Europe", meta: "English" },
  { value: "va", label: "Vatican City", group: "Europe", meta: "Italian" },

  // Oceania
  { value: "au", label: "Australia", group: "Oceania", meta: "English" },
  { value: "fj", label: "Fiji", group: "Oceania", meta: "English" },
  { value: "ki", label: "Kiribati", group: "Oceania", meta: "English" },
  { value: "mh", label: "Marshall Islands", group: "Oceania", meta: "Marshallese" },
  { value: "fm", label: "Micronesia", group: "Oceania", meta: "English" },
  { value: "nr", label: "Nauru", group: "Oceania", meta: "Nauruan" },
  { value: "nz", label: "New Zealand", group: "Oceania", meta: "English" },
  { value: "pw", label: "Palau", group: "Oceania", meta: "Palauan" },
  { value: "pg", label: "Papua New Guinea", group: "Oceania", meta: "English" },
  { value: "ws", label: "Samoa", group: "Oceania", meta: "Samoan" },
  { value: "sb", label: "Solomon Islands", group: "Oceania", meta: "English" },
  { value: "to", label: "Tonga", group: "Oceania", meta: "Tongan" },
  { value: "tv", label: "Tuvalu", group: "Oceania", meta: "Tuvaluan" },
  { value: "vu", label: "Vanuatu", group: "Oceania", meta: "Bislama" },
]
